<?php
class Sabai_Addon_Entity_Model_EntityType extends Sabai_Addon_Entity_Model_Base_EntityType
{
}

class Sabai_Addon_Entity_Model_EntityTypeRepository extends Sabai_Addon_Entity_Model_Base_EntityTypeRepository
{
}