<?php
/* This file has been auto-generated. Do not edit this file directly. */

abstract class Sabai_Addon_System_Model_Base_PermissionCategory extends SabaiFramework_Model_Entity
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('PermissionCategory', $model);
        $this->_vars = array('id' => null, 'permissioncategory_name' => null, 'permissioncategory_title' => null, 'permissioncategory_parent_name' => null, 'permissioncategory_created' => 0, 'permissioncategory_updated' => 0);
    }

    public function __clone()
    {
        $this->_vars = array('id' => null, 'permissioncategory_name' => null, 'permissioncategory_created' => 0, 'permissioncategory_updated' => 0) + $this->_vars;
    }

    public function __toString()
    {
        return $this->__get('name');
    }

    public function initVars(array $arr)
    {
        parent::initVars($arr);
        $this->_vars['id'] = $this->_vars['permissioncategory_name'];
    }

    public function addPermission(Sabai_Addon_System_Model_Permission $entity)
    {
        $entity->PermissionCategory = $this;

        return $this;
    }

    public function removePermission(Sabai_Addon_System_Model_Permission $entity)
    {
        $this->removePermissionById($entity->id);

        return $this;
    }

    public function removePermissionById($id)
    {
        $this->_removeEntityById('permission_id', 'Permission', $id);

        return $this;
    }

    public function createPermission()
    {
        return $this->_createEntity('Permission');
    }

    public function removePermissions()
    {
        $this->_removeEntities('Permission');

        return $this;
    }

    public function __get($name)
    {
        if ($name === 'id')
            return $this->_vars['id'];
        elseif ($name === 'name')
            return $this->_vars['permissioncategory_name'];
        elseif ($name === 'title')
            return $this->_vars['permissioncategory_title'];
        elseif ($name === 'parent_name')
            return $this->_vars['permissioncategory_parent_name'];
        elseif ($name === 'created')
            return $this->_vars['permissioncategory_created'];
        elseif ($name === 'updated')
            return $this->_vars['permissioncategory_updated'];
        elseif ($name === 'Permissions')
            return $this->_fetchEntities('Permission', 'Permissions');
        else
            return $this->fetchObject($name);
    }

    public function __set($name, $value)
    {
        if ($name === 'id')
            $this->_setVar('id', $value);
        elseif ($name === 'name')
            $this->_setVar('permissioncategory_name', $value);
        elseif ($name === 'title')
            $this->_setVar('permissioncategory_title', $value);
        elseif ($name === 'parent_name')
            $this->_setVar('permissioncategory_parent_name', $value);
        elseif ($name === 'Permissions') {
            $this->removePermissions();
            foreach (array_keys($value) as $i) $this->addPermission($value[$i]);
        }
        else
            $this->assignObject($name, $value);
    }

    protected function _initVar($name, $value)
    {
        if ($name === 'permissioncategory_created')
            $this->_vars['permissioncategory_created'] = (int)$value;
        elseif ($name === 'permissioncategory_updated')
            $this->_vars['permissioncategory_updated'] = (int)$value;
        else
            $this->_vars[$name] = $value;
    }
}

abstract class Sabai_Addon_System_Model_Base_PermissionCategoryRepository extends SabaiFramework_Model_EntityRepository
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('PermissionCategory', $model);
    }

    protected function _getCollectionByRowset(SabaiFramework_DB_Rowset $rs)
    {
        return new Sabai_Addon_System_Model_Base_PermissionCategoriesByRowset($rs, $this->_model->create('PermissionCategory'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Sabai_Addon_System_Model_Base_PermissionCategories($this->_model, $entities);
    }
}

class Sabai_Addon_System_Model_Base_PermissionCategoriesByRowset extends SabaiFramework_Model_EntityCollection_Rowset
{
    public function __construct(SabaiFramework_DB_Rowset $rs, Sabai_Addon_System_Model_PermissionCategory $emptyEntity, SabaiFramework_Model $model)
    {
        parent::__construct('PermissionCategories', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(SabaiFramework_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Sabai_Addon_System_Model_Base_PermissionCategories extends SabaiFramework_Model_EntityCollection_Array
{
    public function __construct(SabaiFramework_Model $model, array $entities = array())
    {
        parent::__construct($model, 'PermissionCategories', $entities);
    }
}