<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_System_Model_Base_PermissionCategoryCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'permissioncategory_name',
        'title' => 'permissioncategory_title',
        'parentName' => 'permissioncategory_parent_name',
        'created' => 'permissioncategory_created',
        'updated' => 'permissioncategory_updated',
    );
}