<?php
/* This file has been auto-generated. Do not edit this file directly. */

abstract class Sabai_Addon_System_Model_Base_PermissionCategoryGateway extends SabaiFramework_Model_Gateway
{
    public function getName()
    {
        return 'system_permissioncategory';
    }

    public function getFields()
    {
        return array('permissioncategory_name' => SabaiFramework_Model::KEY_TYPE_VARCHAR, 'permissioncategory_title' => SabaiFramework_Model::KEY_TYPE_VARCHAR, 'permissioncategory_parent_name' => SabaiFramework_Model::KEY_TYPE_VARCHAR, 'permissioncategory_created' => SabaiFramework_Model::KEY_TYPE_INT, 'permissioncategory_updated' => SabaiFramework_Model::KEY_TYPE_INT);
    }

    protected function _getIdFieldName()
    {
        return 'permissioncategory_name';
    }

    protected function _getSelectByIdQuery($id, $fields)
    {
        return sprintf(
            'SELECT %s FROM %ssystem_permissioncategory WHERE permissioncategory_name = %s',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $this->_db->escapeString($id)
        );
    }

    protected function _getSelectByIdsQuery($ids, $fields)
    {
        return sprintf(
            'SELECT %s FROM %ssystem_permissioncategory WHERE permissioncategory_name IN (%s)',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            implode(', ', array_map(array($this->_db, 'escapeString'), $ids))
        );
    }

    protected function _getSelectByCriteriaQuery($criteriaStr, $fields)
    {
        return sprintf(
            'SELECT %1$s FROM %2$ssystem_permissioncategory system_permissioncategory WHERE %3$s',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $criteriaStr
        );
    }

    protected function _getInsertQuery(&$values)
    {
        $values['permissioncategory_created'] = time();
        $values['permissioncategory_updated'] = 0;
        return sprintf('INSERT INTO %ssystem_permissioncategory(permissioncategory_name, permissioncategory_title, permissioncategory_parent_name, permissioncategory_created, permissioncategory_updated) VALUES(%s, %s, %s, %d, %d)', $this->_db->getResourcePrefix(), $this->_db->escapeString($values['permissioncategory_name']), $this->_db->escapeString($values['permissioncategory_title']), $this->_db->escapeString($values['permissioncategory_parent_name']), $values['permissioncategory_created'], $values['permissioncategory_updated']);
    }

    protected function _getUpdateQuery($id, $values)
    {
        $last_update = $values['permissioncategory_updated'];
        $values['permissioncategory_updated'] = time();
        return sprintf('UPDATE %ssystem_permissioncategory SET permissioncategory_title = %s, permissioncategory_parent_name = %s, permissioncategory_updated = %d WHERE permissioncategory_name = %s AND permissioncategory_updated = %d', $this->_db->getResourcePrefix(), $this->_db->escapeString($values['permissioncategory_title']), $this->_db->escapeString($values['permissioncategory_parent_name']), $values['permissioncategory_updated'], $this->_db->escapeString($id), $last_update);
    }

    protected function _getDeleteQuery($id)
    {
        return sprintf('DELETE FROM %1$ssystem_permissioncategory WHERE permissioncategory_name = %2$s', $this->_db->getResourcePrefix(), $this->_db->escapeString($id));
    }

    protected function _getUpdateByCriteriaQuery($criteriaStr, $sets)
    {
        $sets['permissioncategory_updated'] = 'permissioncategory_updated=' . time();
        return sprintf('UPDATE %ssystem_permissioncategory system_permissioncategory SET %s WHERE %s', $this->_db->getResourcePrefix(), implode(', ', $sets), $criteriaStr);
    }

    protected function _getDeleteByCriteriaQuery($criteriaStr)
    {
        return sprintf('DELETE system_permissioncategory FROM %1$ssystem_permissioncategory system_permissioncategory WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    protected function _getCountByCriteriaQuery($criteriaStr)
    {
        return sprintf('SELECT COUNT(*) FROM %1$ssystem_permissioncategory system_permissioncategory WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }
}