<?php
class Sabai_Addon_Widgets_Model_Widget extends Sabai_Addon_Widgets_Model_Base_Widget
{
}

class Sabai_Addon_Widgets_Model_WidgetRepository extends Sabai_Addon_Widgets_Model_Base_WidgetRepository
{
}