<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Form_Model_Base_FieldCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'type' => 'field_type',
        'addon' => 'field_addon',
        'system' => 'field_system',
        'created' => 'field_created',
        'updated' => 'field_updated',
    );
}