<?php
/* This file has been auto-generated. Do not edit this file directly. */

abstract class Sabai_Addon_Form_Model_Base_Field extends SabaiFramework_Model_Entity
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Field', $model);
        $this->_vars = array('id' => null, 'field_type' => null, 'field_addon' => null, 'field_system' => false, 'field_created' => 0, 'field_updated' => 0);
    }

    public function __clone()
    {
        $this->_vars = array('id' => null, 'field_type' => null, 'field_created' => 0, 'field_updated' => 0) + $this->_vars;
    }

    public function __toString()
    {
        return 'Field:' . $this->__get('type');
    }

    public function initVars(array $arr)
    {
        parent::initVars($arr);
        $this->_vars['id'] = $this->_vars['field_type'];
    }

    public function __get($name)
    {
        if ($name === 'id')
            return $this->_vars['id'];
        elseif ($name === 'type')
            return $this->_vars['field_type'];
        elseif ($name === 'addon')
            return $this->_vars['field_addon'];
        elseif ($name === 'system')
            return $this->_vars['field_system'];
        elseif ($name === 'created')
            return $this->_vars['field_created'];
        elseif ($name === 'updated')
            return $this->_vars['field_updated'];
        else
            return $this->fetchObject($name);
    }

    public function __set($name, $value)
    {
        if ($name === 'id')
            $this->_setVar('id', $value);
        elseif ($name === 'type')
            $this->_setVar('field_type', $value);
        elseif ($name === 'addon')
            $this->_setVar('field_addon', $value);
        elseif ($name === 'system')
            $this->_setVar('field_system', $value);
        else
            $this->assignObject($name, $value);
    }

    protected function _initVar($name, $value)
    {
        if ($name === 'field_system')
            $this->_vars['field_system'] = (bool)$value;
        elseif ($name === 'field_created')
            $this->_vars['field_created'] = (int)$value;
        elseif ($name === 'field_updated')
            $this->_vars['field_updated'] = (int)$value;
        else
            $this->_vars[$name] = $value;
    }
}

abstract class Sabai_Addon_Form_Model_Base_FieldRepository extends SabaiFramework_Model_EntityRepository
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Field', $model);
    }

    protected function _getCollectionByRowset(SabaiFramework_DB_Rowset $rs)
    {
        return new Sabai_Addon_Form_Model_Base_FieldsByRowset($rs, $this->_model->create('Field'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Sabai_Addon_Form_Model_Base_Fields($this->_model, $entities);
    }
}

class Sabai_Addon_Form_Model_Base_FieldsByRowset extends SabaiFramework_Model_EntityCollection_Rowset
{
    public function __construct(SabaiFramework_DB_Rowset $rs, Sabai_Addon_Form_Model_Field $emptyEntity, SabaiFramework_Model $model)
    {
        parent::__construct('Fields', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(SabaiFramework_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Sabai_Addon_Form_Model_Base_Fields extends SabaiFramework_Model_EntityCollection_Array
{
    public function __construct(SabaiFramework_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Fields', $entities);
    }
}