<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Field_Model_Base_TypeCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'type_name',
        'addon' => 'type_addon',
        'created' => 'type_created',
        'updated' => 'type_updated',
    );
}