<?php
/* This file has been auto-generated. Do not edit this file directly. */

abstract class Sabai_Addon_Field_Model_Base_Type extends SabaiFramework_Model_Entity
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Type', $model);
        $this->_vars = array('id' => null, 'type_name' => null, 'type_addon' => null, 'type_created' => 0, 'type_updated' => 0);
    }

    public function __clone()
    {
        $this->_vars = array('id' => null, 'type_name' => null, 'type_created' => 0, 'type_updated' => 0) + $this->_vars;
    }

    public function __toString()
    {
        return $this->__get('name');
    }

    public function initVars(array $arr)
    {
        parent::initVars($arr);
        $this->_vars['id'] = $this->_vars['type_name'];
    }

    public function __get($name)
    {
        if ($name === 'id')
            return $this->_vars['id'];
        elseif ($name === 'name')
            return $this->_vars['type_name'];
        elseif ($name === 'addon')
            return $this->_vars['type_addon'];
        elseif ($name === 'created')
            return $this->_vars['type_created'];
        elseif ($name === 'updated')
            return $this->_vars['type_updated'];
        else
            return $this->fetchObject($name);
    }

    public function __set($name, $value)
    {
        if ($name === 'id')
            $this->_setVar('id', $value);
        elseif ($name === 'name')
            $this->_setVar('type_name', $value);
        elseif ($name === 'addon')
            $this->_setVar('type_addon', $value);
        else
            $this->assignObject($name, $value);
    }

    protected function _initVar($name, $value)
    {
        if ($name === 'type_created')
            $this->_vars['type_created'] = (int)$value;
        elseif ($name === 'type_updated')
            $this->_vars['type_updated'] = (int)$value;
        else
            $this->_vars[$name] = $value;
    }
}

abstract class Sabai_Addon_Field_Model_Base_TypeRepository extends SabaiFramework_Model_EntityRepository
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Type', $model);
    }

    protected function _getCollectionByRowset(SabaiFramework_DB_Rowset $rs)
    {
        return new Sabai_Addon_Field_Model_Base_TypesByRowset($rs, $this->_model->create('Type'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Sabai_Addon_Field_Model_Base_Types($this->_model, $entities);
    }
}

class Sabai_Addon_Field_Model_Base_TypesByRowset extends SabaiFramework_Model_EntityCollection_Rowset
{
    public function __construct(SabaiFramework_DB_Rowset $rs, Sabai_Addon_Field_Model_Type $emptyEntity, SabaiFramework_Model $model)
    {
        parent::__construct('Types', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(SabaiFramework_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Sabai_Addon_Field_Model_Base_Types extends SabaiFramework_Model_EntityCollection_Array
{
    public function __construct(SabaiFramework_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Types', $entities);
    }
}