<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Field_Model_Base_WidgetCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'widget_name',
        'addon' => 'widget_addon',
        'created' => 'widget_created',
        'updated' => 'widget_updated',
    );
}