<?php
/* This file has been auto-generated. Do not edit this file directly. */

abstract class Sabai_Addon_Field_Model_Base_Widget extends SabaiFramework_Model_Entity
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Widget', $model);
        $this->_vars = array('id' => null, 'widget_name' => null, 'widget_addon' => null, 'widget_created' => 0, 'widget_updated' => 0);
    }

    public function __clone()
    {
        $this->_vars = array('id' => null, 'widget_name' => null, 'widget_created' => 0, 'widget_updated' => 0) + $this->_vars;
    }

    public function __toString()
    {
        return $this->__get('name');
    }

    public function initVars(array $arr)
    {
        parent::initVars($arr);
        $this->_vars['id'] = $this->_vars['widget_name'];
    }

    public function __get($name)
    {
        if ($name === 'id')
            return $this->_vars['id'];
        elseif ($name === 'name')
            return $this->_vars['widget_name'];
        elseif ($name === 'addon')
            return $this->_vars['widget_addon'];
        elseif ($name === 'created')
            return $this->_vars['widget_created'];
        elseif ($name === 'updated')
            return $this->_vars['widget_updated'];
        else
            return $this->fetchObject($name);
    }

    public function __set($name, $value)
    {
        if ($name === 'id')
            $this->_setVar('id', $value);
        elseif ($name === 'name')
            $this->_setVar('widget_name', $value);
        elseif ($name === 'addon')
            $this->_setVar('widget_addon', $value);
        else
            $this->assignObject($name, $value);
    }

    protected function _initVar($name, $value)
    {
        if ($name === 'widget_created')
            $this->_vars['widget_created'] = (int)$value;
        elseif ($name === 'widget_updated')
            $this->_vars['widget_updated'] = (int)$value;
        else
            $this->_vars[$name] = $value;
    }
}

abstract class Sabai_Addon_Field_Model_Base_WidgetRepository extends SabaiFramework_Model_EntityRepository
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Widget', $model);
    }

    protected function _getCollectionByRowset(SabaiFramework_DB_Rowset $rs)
    {
        return new Sabai_Addon_Field_Model_Base_WidgetsByRowset($rs, $this->_model->create('Widget'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Sabai_Addon_Field_Model_Base_Widgets($this->_model, $entities);
    }
}

class Sabai_Addon_Field_Model_Base_WidgetsByRowset extends SabaiFramework_Model_EntityCollection_Rowset
{
    public function __construct(SabaiFramework_DB_Rowset $rs, Sabai_Addon_Field_Model_Widget $emptyEntity, SabaiFramework_Model $model)
    {
        parent::__construct('Widgets', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(SabaiFramework_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Sabai_Addon_Field_Model_Base_Widgets extends SabaiFramework_Model_EntityCollection_Array
{
    public function __construct(SabaiFramework_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Widgets', $entities);
    }
}