<?php
class Sabai_Addon_PaidListings_Model_OrderLog extends Sabai_Addon_PaidListings_Model_Base_OrderLog
{
}

class Sabai_Addon_PaidListings_Model_OrderLogRepository extends Sabai_Addon_PaidListings_Model_Base_OrderLogRepository
{
}