<?php
class Sabai_Addon_PaidListings_Model_OrderItemMeta extends Sabai_Addon_PaidListings_Model_Base_OrderItemMeta
{
}

class Sabai_Addon_PaidListings_Model_OrderItemMetaRepository extends Sabai_Addon_PaidListings_Model_Base_OrderItemMetaRepository
{
}