<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Entity_Model_Base_EntityTypeCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'entitytype_name',
        'addon' => 'entitytype_addon',
        'created' => 'entitytype_created',
        'updated' => 'entitytype_updated',
    );
}