<?php
/* This file has been auto-generated. Do not edit this file directly. */

abstract class Sabai_Addon_Entity_Model_Base_FieldStorage extends SabaiFramework_Model_Entity
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('FieldStorage', $model);
        $this->_vars = array('id' => null, 'fieldstorage_name' => null, 'fieldstorage_addon' => null, 'fieldstorage_created' => 0, 'fieldstorage_updated' => 0);
    }

    public function __clone()
    {
        $this->_vars = array('id' => null, 'fieldstorage_name' => null, 'fieldstorage_created' => 0, 'fieldstorage_updated' => 0) + $this->_vars;
    }

    public function __toString()
    {
        return $this->__get('name');
    }

    public function initVars(array $arr)
    {
        parent::initVars($arr);
        $this->_vars['id'] = $this->_vars['fieldstorage_name'];
    }

    public function __get($name)
    {
        if ($name === 'id')
            return $this->_vars['id'];
        elseif ($name === 'name')
            return $this->_vars['fieldstorage_name'];
        elseif ($name === 'addon')
            return $this->_vars['fieldstorage_addon'];
        elseif ($name === 'created')
            return $this->_vars['fieldstorage_created'];
        elseif ($name === 'updated')
            return $this->_vars['fieldstorage_updated'];
        else
            return $this->fetchObject($name);
    }

    public function __set($name, $value)
    {
        if ($name === 'id')
            $this->_setVar('id', $value);
        elseif ($name === 'name')
            $this->_setVar('fieldstorage_name', $value);
        elseif ($name === 'addon')
            $this->_setVar('fieldstorage_addon', $value);
        else
            $this->assignObject($name, $value);
    }

    protected function _initVar($name, $value)
    {
        if ($name === 'fieldstorage_created')
            $this->_vars['fieldstorage_created'] = (int)$value;
        elseif ($name === 'fieldstorage_updated')
            $this->_vars['fieldstorage_updated'] = (int)$value;
        else
            $this->_vars[$name] = $value;
    }
}

abstract class Sabai_Addon_Entity_Model_Base_FieldStorageRepository extends SabaiFramework_Model_EntityRepository
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('FieldStorage', $model);
    }

    protected function _getCollectionByRowset(SabaiFramework_DB_Rowset $rs)
    {
        return new Sabai_Addon_Entity_Model_Base_FieldStoragesByRowset($rs, $this->_model->create('FieldStorage'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Sabai_Addon_Entity_Model_Base_FieldStorages($this->_model, $entities);
    }
}

class Sabai_Addon_Entity_Model_Base_FieldStoragesByRowset extends SabaiFramework_Model_EntityCollection_Rowset
{
    public function __construct(SabaiFramework_DB_Rowset $rs, Sabai_Addon_Entity_Model_FieldStorage $emptyEntity, SabaiFramework_Model $model)
    {
        parent::__construct('FieldStorages', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(SabaiFramework_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Sabai_Addon_Entity_Model_Base_FieldStorages extends SabaiFramework_Model_EntityCollection_Array
{
    public function __construct(SabaiFramework_Model $model, array $entities = array())
    {
        parent::__construct($model, 'FieldStorages', $entities);
    }
}