<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Entity_Model_Base_FieldStorageCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'fieldstorage_name',
        'addon' => 'fieldstorage_addon',
        'created' => 'fieldstorage_created',
        'updated' => 'fieldstorage_updated',
    );
}