<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_PaidListings_Model_Base_FeatureCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'feature_name',
        'addon' => 'feature_addon',
        'settings' => 'feature_settings',
        'created' => 'feature_created',
        'updated' => 'feature_updated',
    );
}