<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_PaidListings_Model_Base_OrderCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'entityBundleName' => 'order_entity_bundle_name',
        'entityId' => 'order_entity_id',
        'status' => 'order_status',
        'price' => 'order_price',
        'transactionId' => 'order_transaction_id',
        'currency' => 'order_currency',
        'gateway' => 'order_gateway',
        'gatewayData' => 'order_gateway_data',
        'planType' => 'order_plan_type',
        'id' => 'order_id',
        'created' => 'order_created',
        'updated' => 'order_updated',
        'planId' => 'order_plan_id',
        'userId' => 'order_user_id',
    );
}