<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_PaidListings_Model_Base_OrderItemCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'status' => 'orderitem_status',
        'id' => 'orderitem_id',
        'created' => 'orderitem_created',
        'updated' => 'orderitem_updated',
        'featureName' => 'orderitem_feature_name',
        'orderId' => 'orderitem_order_id',
    );
}