<?php
/* This file has been auto-generated. Do not edit this file directly. */

abstract class Sabai_Addon_PaidListings_Model_Base_OrderItemMeta extends SabaiFramework_Model_Entity
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('OrderItemMeta', $model);
        $this->_vars = array('orderitemmeta_key' => null, 'orderitemmeta_value' => null, 'orderitemmeta_id' => 0, 'orderitemmeta_created' => 0, 'orderitemmeta_updated' => 0, 'orderitemmeta_orderitem_id' => 0);
    }

    public function __clone()
    {
        $this->_vars = array('orderitemmeta_id' => 0, 'orderitemmeta_created' => 0, 'orderitemmeta_updated' => 0) + $this->_vars;
    }

    public function __toString()
    {
        return 'OrderItemMeta:' . $this->__get('id');
    }

    public function __get($name)
    {
        if ($name === 'key')
            return $this->_vars['orderitemmeta_key'];
        elseif ($name === 'value')
            return $this->_vars['orderitemmeta_value'];
        elseif ($name === 'id')
            return $this->_vars['orderitemmeta_id'];
        elseif ($name === 'created')
            return $this->_vars['orderitemmeta_created'];
        elseif ($name === 'updated')
            return $this->_vars['orderitemmeta_updated'];
        elseif ($name === 'orderitem_id')
            return $this->_vars['orderitemmeta_orderitem_id'];
        elseif ($name === 'OrderItem')
            return $this->_fetchEntity('OrderItem', 'orderitem_id');
        else
            return $this->fetchObject($name);
    }

    public function __set($name, $value)
    {
        if ($name === 'key')
            $this->_setVar('orderitemmeta_key', $value);
        elseif ($name === 'value')
            $this->_setVar('orderitemmeta_value', $value);
        elseif ($name === 'id')
            $this->_setVar('orderitemmeta_id', $value);
        elseif ($name === 'orderitem_id')
            $this->_assignEntityById('OrderItem', $value, 'orderitemmeta_orderitem_id');
        elseif ($name === 'OrderItem') {
            $_value = is_array($value) ? $value[0] : $value;
            if (is_object($_value)) {
                $this->_assignEntity($_value, 'orderitemmeta_orderitem_id');
            } else {
                $this->_assignEntityById('OrderItem', $_value, 'orderitemmeta_orderitem_id');
            }
        }
        else
            $this->assignObject($name, $value);
    }

    protected function _initVar($name, $value)
    {
        if ($name === 'orderitemmeta_id')
            $this->_vars['orderitemmeta_id'] = (int)$value;
        elseif ($name === 'orderitemmeta_created')
            $this->_vars['orderitemmeta_created'] = (int)$value;
        elseif ($name === 'orderitemmeta_updated')
            $this->_vars['orderitemmeta_updated'] = (int)$value;
        elseif ($name === 'orderitemmeta_orderitem_id')
            $this->_vars['orderitemmeta_orderitem_id'] = (int)$value;
        else
            $this->_vars[$name] = $value;
    }
}

abstract class Sabai_Addon_PaidListings_Model_Base_OrderItemMetaRepository extends SabaiFramework_Model_EntityRepository
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('OrderItemMeta', $model);
    }

    public function fetchByOrderItem($id, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeign('orderitemmeta_orderitem_id', $id, $limit, $offset, $sort, $order);
    }

    public function paginateByOrderItem($id, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntity('OrderItem', $id, $perpage, $sort, $order);
    }

    public function countByOrderItem($id)
    {
        return $this->_countByForeign('orderitemmeta_orderitem_id', $id);
    }

    public function fetchByOrderItemAndCriteria($id, SabaiFramework_Criteria $criteria, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeignAndCriteria('orderitemmeta_orderitem_id', $id, $criteria, $limit, $offset, $sort, $order);
    }

    public function paginateByOrderItemAndCriteria($id, SabaiFramework_Criteria $criteria, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntityAndCriteria('OrderItem', $id, $criteria, $perpage, $sort, $order);
    }

    public function countByOrderItemAndCriteria($id, SabaiFramework_Criteria $criteria)
    {
        return $this->_countByForeignAndCriteria('orderitemmeta_orderitem_id', $id, $criteria);
    }

    protected function _getCollectionByRowset(SabaiFramework_DB_Rowset $rs)
    {
        return new Sabai_Addon_PaidListings_Model_Base_OrderItemMetasByRowset($rs, $this->_model->create('OrderItemMeta'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Sabai_Addon_PaidListings_Model_Base_OrderItemMetas($this->_model, $entities);
    }
}

class Sabai_Addon_PaidListings_Model_Base_OrderItemMetasByRowset extends SabaiFramework_Model_EntityCollection_Rowset
{
    public function __construct(SabaiFramework_DB_Rowset $rs, Sabai_Addon_PaidListings_Model_OrderItemMeta $emptyEntity, SabaiFramework_Model $model)
    {
        parent::__construct('OrderItemMetas', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(SabaiFramework_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Sabai_Addon_PaidListings_Model_Base_OrderItemMetas extends SabaiFramework_Model_EntityCollection_Array
{
    public function __construct(SabaiFramework_Model $model, array $entities = array())
    {
        parent::__construct($model, 'OrderItemMetas', $entities);
    }
}