<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_PaidListings_Model_Base_OrderLogCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'message' => 'orderlog_message',
        'status' => 'orderlog_status',
        'isError' => 'orderlog_is_error',
        'id' => 'orderlog_id',
        'created' => 'orderlog_created',
        'updated' => 'orderlog_updated',
        'orderId' => 'orderlog_order_id',
        'orderitemId' => 'orderlog_orderitem_id',
    );
}