<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_PaidListings_Model_Base_OrderItemMetaCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'key' => 'orderitemmeta_key',
        'value' => 'orderitemmeta_value',
        'id' => 'orderitemmeta_id',
        'created' => 'orderitemmeta_created',
        'updated' => 'orderitemmeta_updated',
        'orderitemId' => 'orderitemmeta_orderitem_id',
    );
}