<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_GoogleMaps_Model_Base_GeocodeCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'query' => 'geocode_query',
        'hash' => 'geocode_hash',
        'lat' => 'geocode_lat',
        'lng' => 'geocode_lng',
        'address' => 'geocode_address',
        'hits' => 'geocode_hits',
        'viewport' => 'geocode_viewport',
        'id' => 'geocode_id',
        'created' => 'geocode_created',
        'updated' => 'geocode_updated',
    );
}