<?php
/* This file has been auto-generated. Do not edit this file directly. */

abstract class Sabai_Addon_GoogleMaps_Model_Base_Geocode extends SabaiFramework_Model_Entity
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Geocode', $model);
        $this->_vars = array('geocode_query' => null, 'geocode_hash' => null, 'geocode_lat' => 0, 'geocode_lng' => 0, 'geocode_address' => null, 'geocode_hits' => 1, 'geocode_viewport' => null, 'geocode_id' => 0, 'geocode_created' => 0, 'geocode_updated' => 0);
    }

    public function __clone()
    {
        $this->_vars = array('geocode_id' => 0, 'geocode_created' => 0, 'geocode_updated' => 0) + $this->_vars;
    }

    public function __toString()
    {
        return 'Geocode:' . $this->__get('id');
    }

    public function __get($name)
    {
        if ($name === 'query')
            return $this->_vars['geocode_query'];
        elseif ($name === 'hash')
            return $this->_vars['geocode_hash'];
        elseif ($name === 'lat')
            return $this->_vars['geocode_lat'];
        elseif ($name === 'lng')
            return $this->_vars['geocode_lng'];
        elseif ($name === 'address')
            return $this->_vars['geocode_address'];
        elseif ($name === 'hits')
            return $this->_vars['geocode_hits'];
        elseif ($name === 'viewport')
            return $this->_vars['geocode_viewport'];
        elseif ($name === 'id')
            return $this->_vars['geocode_id'];
        elseif ($name === 'created')
            return $this->_vars['geocode_created'];
        elseif ($name === 'updated')
            return $this->_vars['geocode_updated'];
        else
            return $this->fetchObject($name);
    }

    public function __set($name, $value)
    {
        if ($name === 'query')
            $this->_setVar('geocode_query', $value);
        elseif ($name === 'hash')
            $this->_setVar('geocode_hash', $value);
        elseif ($name === 'lat')
            $this->_setVar('geocode_lat', $value);
        elseif ($name === 'lng')
            $this->_setVar('geocode_lng', $value);
        elseif ($name === 'address')
            $this->_setVar('geocode_address', $value);
        elseif ($name === 'hits')
            $this->_setVar('geocode_hits', $value);
        elseif ($name === 'viewport')
            $this->_setVar('geocode_viewport', $value);
        elseif ($name === 'id')
            $this->_setVar('geocode_id', $value);
        else
            $this->assignObject($name, $value);
    }

    protected function _initVar($name, $value)
    {
        if ($name === 'geocode_lat')
            $this->_vars['geocode_lat'] = (float)$value;
        elseif ($name === 'geocode_lng')
            $this->_vars['geocode_lng'] = (float)$value;
        elseif ($name === 'geocode_hits')
            $this->_vars['geocode_hits'] = (int)$value;
        elseif ($name === 'geocode_id')
            $this->_vars['geocode_id'] = (int)$value;
        elseif ($name === 'geocode_created')
            $this->_vars['geocode_created'] = (int)$value;
        elseif ($name === 'geocode_updated')
            $this->_vars['geocode_updated'] = (int)$value;
        else
            $this->_vars[$name] = $value;
    }
}

abstract class Sabai_Addon_GoogleMaps_Model_Base_GeocodeRepository extends SabaiFramework_Model_EntityRepository
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Geocode', $model);
    }

    protected function _getCollectionByRowset(SabaiFramework_DB_Rowset $rs)
    {
        return new Sabai_Addon_GoogleMaps_Model_Base_GeocodesByRowset($rs, $this->_model->create('Geocode'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Sabai_Addon_GoogleMaps_Model_Base_Geocodes($this->_model, $entities);
    }
}

class Sabai_Addon_GoogleMaps_Model_Base_GeocodesByRowset extends SabaiFramework_Model_EntityCollection_Rowset
{
    public function __construct(SabaiFramework_DB_Rowset $rs, Sabai_Addon_GoogleMaps_Model_Geocode $emptyEntity, SabaiFramework_Model $model)
    {
        parent::__construct('Geocodes', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(SabaiFramework_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Sabai_Addon_GoogleMaps_Model_Base_Geocodes extends SabaiFramework_Model_EntityCollection_Array
{
    public function __construct(SabaiFramework_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Geocodes', $entities);
    }
}